name: Linlin DNS UpdateRules
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

  push:
    branches:
      - main #2020年10月后github新建仓库默认分支改为main，注意更改

  release:
    types:
      - published

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 获取最新代码
        run: |
          git init
          git config --local user.email "1732509260@qq.com"
          git config --local user.name "Linlin"
          git fetch --all
          git reset --hard origin/main
          git pull
          git branch -m main

      - name: 运行
        run: |
          npm install
          node index

      - name: 更新文件
        run: |
          git add --all
          git commit -m "Updated at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')（北京时间）"
          git push -u origin -f

      - name: 删除 workflow 运行记录
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
